title: Single RNA-seq data analysis with R
description: [/logos/excelerate.png](/logos/excelerate.png)
theme: jekyll-theme-leap-day
url: https://olgadet.github.io/excelerate-scRNAseq/
use_logo: true
logo: /logos/excelerate.png
search_in_topnav: true
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
