title: Single RNA-seq data analysis with R
theme: jekyll-theme-leap-day
url: https://olgadet.github.io/excelerate-scRNAseq/
logo: logos/excelerate.png
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
